name: MA Technicals

on:
  workflow_dispatch:   # manual trigger
  schedule:
    - cron: "32 * * * *"

jobs:
  calc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run calculation job
        env:
          PG_DSN: ${{ secrets.PG_DSN_CRYPTO }}        # <-- DSN from secret
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}        # <-- DSN from secret
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}        # <-- DSN from secret
        run: |
          python -m src.run_signals
